name: Update Rubber Prices

on:
  schedule:
    - cron: "0 6 * * *"  # 6 AM UTC = 11:30 AM IST
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v3

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated from v4
        with:
          python-version: "3.10"  # Recommended bump from 3.9
          cache: 'pip'  # Add caching for faster builds

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python scraper.py
